### ISSUE TITLE
Contributor's Guide changes

### ISSUE THREAD

**Issue by r-ford** [ProjectPythiaCookbooks/.github#2]
Any changes that need to be made to the [Cookbook Contributor's Guide](https://github.com/ProjectPythiaCookbooks/.github/blob/main/CONTRIBUTING.md) can be listed here.

- [x] Add: change all `cookbook-dev` in `.github/workflows` to `<your-cookbook>-dev`
- [x] Clarify changing environment name as in ProjectPythiaCookbooks/cookbook-template#27 
- [x] Update what should be included in `README`, now that it replaced `landing-page`
- [x] Update the about section of your repository to include a description and topic tags. This will be used for the gallery card description and tags.
- [x] Change any `ProjectPythiaTutorials` to `ProjectPythiaCookbooks`
- [x] Move to `.github` repo
- [x] Add instructions to edit binder badge
- [x] Add section on contributing to an existing cookbook
- [x] Add: edit `_config.yml` title, author, etc.
- [x] Add line about `thumbnail.png`

**Comment by brian-rose** [comment]
Binder badge instructions are handled in #4

**Comment by brian-rose** [comment]
I'm not sure if we ever finished the above task list? But we'll need some new changes to account for recent updates in the Template.

**Comment by r-ford** [comment]
Looks like pretty much everything was addressed. I think a new issue for changes related to the new infrastructure makes sense.
